# Base image
FROM python:3.11

# Set working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application files
COPY . .

# Expose the port (if applicable)
EXPOSE 5672

# Start the news generator
CMD ["python", "news_generator.py"]
